### ISSUE TITLE
NTR: bacterias and fungal species

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#14]
Could you please add the following species to be used with bacterial/fungal treatment, please? 

- Cryptococcus neoformans ; Taxonomy ID: 5207
- Porphyromonas gingivalis ; Taxonomy ID: 837
- Porphyromonas gingivalis W83 ; Taxonomy ID: 242619
- Porphyromonas gingivalis ATCC 33277 ; Taxonomy ID: 431947
- Porphyromonas gingivalis 381 ; Taxonomy ID: 1403335

Thank you!

**Comment by ybradford** [comment]
terms are added, closing.
