### ISSUE TITLE
NTR: bacteria Waddlia chondrophila 

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#15]
Could you add the following species in the list of bacteria to use in ZECO, please?

- Waddlia chondrophila ; Taxonomy ID: 71667
- Waddlia chondrophila WSU 86-1044 ; Taxonomy ID: 716544

Thank you!

**Comment by ybradford** [comment]
@sabrinatoro added to list. closing case.
