### ISSUE TITLE
 Chlamydomonas reinhardtii

### ISSUE THREAD

**Issue by cerivs** [ybradford/zebrafish-experimental-conditions-ontology#16]
Chlamydomonas reinhardtii  ZDB-PUB-170214-243

**Comment by ybradford** [comment]
We currently do not have Viridiplantae (green plants) as a root term in the NCBI Taxon slim. This term is a child of green plants.  This is the first term request that falls under this root term. I'm not going to add the root term or child term right now. Please reopen case  if you think we have a significant number of publications that would benefit from adding this term.
