### ISSUE TITLE
dietary challenge (nutrient increased/decreased) terms for FB

### ISSUE THREAD

**Issue by sfexova** [ybradford/zebrafish-experimental-conditions-ontology#19]
Hi Yvonne
as we discussed at the VC could you please incorporate the following terms (or something similar) to ZECO:

--- all of these are intended to be paired with a ChEBI entry during curation ---
nutrient decreased (levels of a nutrient are decreased relative to standard diet)
nutrient increased (levels of a nutrient are increased relative to standard diet)
nutrient added (a particular nutrient whose levels in the diet are known or presumed to be either nil or negligible is added to the food)
diet limited to

These are intended to cover all kinds of nutritional challenges - whether they involve micro- or macro- nutrients, so I tried to think of as general terms as possible.

I'm attaching excerpts (with PMIDs) from several papers to illustrate the kind of conditions we'd like to capture using the proposed terms. Let me know if you'd like more examples or need any additional info.
Thanks, Silvie
[ZECO_term_request_examples.docx](https://github.com/ybradford/zebrafish-experimental-conditions-ontology/files/1217708/ZECO_term_request_examples.docx)

**Comment by ybradford** [comment]
@sfexova I've added 'nutrient decreased', 'nutrient increased' to the file.
