### ISSUE TITLE
New bacteria request: Burkholderia species

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#24]
Could you please add the following bacteria species to the taxon file? Thanks! 

Burkholderia cenocepacia
Taxonomy ID: 95486

Burkholderia cepacia
Taxonomy ID: 292

Burkholderia stabilis
Taxonomy ID: 95485

**Comment by ybradford** [comment]
these are now available on prod.
