### ISSUE TITLE
NTRs cold damage

### ISSUE THREAD

**Issue by cerivs** [ybradford/zebrafish-experimental-conditions-ontology#3]
ZDB-PUB-160525-13 uses cryoinjury or cryoablation to "amputate" a fin. 
New term
cold damage
Physical alteration which uses cold to damage the anatomical structure, cell, or organ.

cryoablation
Targeted destruction of an anatomical structure by freezing.
is_a cold damage
is_a ablation

**Comment by ybradford** [comment]
@cerivs added terms to zeco.
