### ISSUE TITLE
 Listeria monocytogenes for taxon list

### ISSUE THREAD

**Issue by cerivs** [ybradford/zebrafish-experimental-conditions-ontology#34]
Listeria monocytogenes
Taxonomy ID: 1639 

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1639&lvl=3&lin=f&keep=1&srchmode=1&unlock

**Comment by ybradford** [comment]
added to file, waiting for push to prod

**Comment by ybradford** [comment]
this is now available on prod
