### ISSUE TITLE
Broken zeco.obo release

### ISSUE THREAD

**Issue by matentzn** [ybradford/zebrafish-experimental-conditions-ontology#43]
@ybradford I think zeco.obo is fixed again! Lets see what @sierra-moxon gets when she loads ZECO again into your system. You can close the issue when it is confirmed.

Regarding the IRIs, I have changed my mind. It would be good to have OBO style IRIs, but to be honest, in order to adhere to good standards, we would have to obsolete the whole ontology and create new classes for everything; this is not worth it. The ODK supports multiple namespaces, so no problems here. I would suggest you check your Protege new entity settings for each ontology you edit; this is what caused this confusion! If you still want to change all IRIs, we need to double-check with ZFIN first how they are referring the ZECO terms internally; it can cause them a bit of headache if suddenly ALL IRIs are different. I believe this issue can be closed!

**Comment by ybradford** [comment]
@matentzn so I think the IRI only got messed up in this latest release with ODK and protege 5.5.. This is what I had previously http://purl.obolibrary.org/obo/zp.owl . This is from an older version http://purl.obolibrary.org/obo/zp/releases/2019-02-27/zp.owl that I opened in protege 5.2.  So either we need to revert what was done in ODK or update to what I had previously.

**Comment by ybradford** [comment]
@matentzn I think you fixed this already? I'm closing and we can re-open if it is still an issue.

**Comment by matentzn** [comment]
yep, fixed
