### ISSUE TITLE
Taxon request: pseudomonas phage

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#46]
Please, add the following 4 virus to the taxon list. 
Thanks

- Pseudomonas phage vB_PaeP_PYO2
Taxonomy ID: 2034342

- Pseudomonas phage vB_PaeP_DEV
Taxonomy ID: 2034344

- Pseudomonas phage vB_PaeM_E215
Taxonomy ID: 2034347

- Pseudomonas phage vB_PaeM_E217
Taxonomy ID: 2034346

**Comment by ybradford** [comment]
these have been added to the file and should be available on prod.
