### ISSUE TITLE
more bacterium for taxon list 

### ISSUE THREAD

**Issue by cerivs** [ybradford/zebrafish-experimental-conditions-ontology#47]
ZDB-PUB-180614-4  (putting human microbes in zebrafish)

Clostridioides difficile  
Taxonomy ID: 1496

 Bacillus clausii
Taxonomy ID: 79880

I'm not sure if we want more hierarchy but if you want to add a parent genus Bacillus the taxon ID is Taxonomy ID: 1386

**Comment by ybradford** [comment]
this is available on prod.
