### ISSUE TITLE
NTR : food increased availability

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#5]
NTR : food increased availability
- synonym: overfeeding
- example: ZDB-PUB-151201-6
- definition: diet condition in which the availability of food is in higher supply compared to controlled conditions
- ontology: 
Child of “food availability” (ZECO:0000113)
“Unlimited availability” (ZECO:0000116) could become a child of “overfeeding” 

I believe "overnutrition" could also be a synonym of "food increased availability"
- example: ZDB-PUB-151001-5 ; ZDB-PUB-140402-15 ; 
- The publications for which this term would be used define “overnutrition” as “diet with chicken egg yolk”. Since the control experiments in these studies are “unfed fish”, it seems correct that "overnutrition" is a synonym of “food increased availability” (at least in this context)

Thank you! 
Sabrina

**Comment by ybradford** [comment]
added terms to zeco. did not add 'overnutrition' as synonym
