### ISSUE TITLE
NTR: microgravity/increase gravity/change in gravity branch

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#56]
[need change in ontology]

### **NTR: microgravity (or decreased gravity)**
Preferred term label
microgravity

Synonyms
decreased gravity

Textual definition
Experimental condition in which gravity forces are smaller than in control conditions. Examples of a microgravity condition could be trips to outerspace.

Suggested parent term
gravity (ZECO:0000154) 

Attribution
ZDB-PUB-190310-2

### **NTR: increased gravity**
Preferred term label
increased gravity

Textual definition
Experimental condition in which gravity forces are greater than in control conditions. Examples of am increased gravity condition could be in the form of centrifugal forces 

Suggested parent term
gravity (ZECO:0000154) 

### **change in the ontolgy**
gravity (ZECO:0000154) currently represents both increased and decreased gravity (based on the definition. This term should become the parent of both increased/decreased gravity. 
Note that the definition should be reviewed as "gravity forces" are not applied in the case of microgravity. 
Current definition:  Experimental  condition in which gravity forces are applied. For zebrafish, this can  be in the form of centrifugal forces or trips to outerspace.
Proposed definition: Experimental  condition in which gravity forces are different compared to control conditions. For zebrafish, this can  be in the form of centrifugal forces or trips to outerspace.

**Comment by ybradford** [comment]
@sabrinatoro this has been added and should be available on prod
