### ISSUE TITLE
NTR : undercrowding/Low density 

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#6]
This term would be the opposite of overcrowding. 
In ZDB-PUB-150325-6, the authors use the terms "low density" and "high density" of fish. 

1) NTR: undercrowding
- synonym: low density
- definition: Housing condition in which the enclosure of the fish is undercrowded or contains a low amount of fish or obstacles that reduce the available space of the enclosure.
- ontology: child of housing conditions (ZECO:0000140)

2) synonym of "overcrowding" (ZECO:0000142) : high density

The definition of these terms include obstacles in the enclosure. Maybe we can make these terms (or new terms? whatever work best for the ontology) more specific to the "animal density". 
In this case, the ontology could be: 
- housing conditions (ZECO:0000140)
--animal density (New term)
--- low animal density (synonym: undercrowded)
--- high animal density (synonym: overcrowded) 

Please let me know if you have questions or if I can do anything to help! 
Thanks
sabrina

**Comment by ybradford** [comment]
added term to zeco. removed 'obstacles' from definition; terms are intended to be about population density.
