### ISSUE TITLE
NTR: burn / thermal injury / cauterization

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#60]
**NTR 1 : thermal injury**

## Preferred term label

thermal injury

## Synonyms

burn

## Textual definition

Targeted destruction of an anatomical structure by burning.

## Suggested parent term

ZECO:0000229 (physical alteration)

**NTR 2 : cauterization**

## Preferred term label

cauterization

## Synonyms

wound burning

## Textual definition

Targeted burning of a part of an anatomical structure to remove or close off a part of it.

## Suggested parent term

thermal injury (NTR in this ticket)

These NTR are needed for curation of PMID:31259685 (ZDB-PUB-190702-4)

**Comment by ybradford** [comment]
@sabrinatoro there are several ways to cauterize a tissue - cold or hot instrument, electrical current, chemical. I was thinking that I can add cauterization but not make it a child of thermal injury. Would that work for you?

**Comment by sabrinatoro** [comment]
@ybradford 
Could you make "cauterize" (because I think it is a useful term in general) AND "cauterize with heat" (or something like that)?
The authors were really specific about using heat (they show that the method they use have different effect), so I want to make sure I am recording their work correctly (otherwise we might have to go back and correct later). 
Thanks

**Comment by ybradford** [comment]
@sabrinatoro yes I do cauterize as a child of physical alteration and a 'cauterize with heat' or similar child term. I will also make thermal injury, but no make cauterize a child of it

**Comment by sabrinatoro** [comment]
@ybradford 
Sounds good! Thank you.

**Comment by ybradford** [comment]
@sabrinatoro this has been added and should be available on prod
