### ISSUE TITLE
NTR:  compression injury

### ISSUE THREAD

**Issue by cerivs** [ybradford/zebrafish-experimental-conditions-ontology#61]
For new term requests, please provide the following information:

## Preferred term label
compression injury

## Synonyms
crush injury 

## Textual definition
An injury that occurs because of pressure from a heavy object onto a body part. A compression injury may also arise from squeezing of a body part between two objects. https://www.medicinenet.com/crush_injury/definition.htm

## Suggested parent term
 physical alteration ZECO:0000229 

## Attribution
ORCiD 0000-0002-2244-7917

**Comment by ybradford** [comment]
this has been added and should be available on prod.
