### ISSUE TITLE
NTR: gavage

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#8]
I would like to request a new term: 
term name: gavage
definition: administration of food or drugs by force, typically through a tube leading down the throat to the stomach.

This term could have 2 children: 
1) chemical treatment by gavage 
This term would have 2 parents: gavage and chemical treatment (ZECO:0000111)
[see ZDB-PUB-160804-16]
This term would require the use of a Chebi term
2) food gavage
this term would have 2 parents: gavage and diet (maybe) or food availability? 

Gavage Parentage: I am not sure where this term should be in the ontology. It is not in diet since gavage can be of either food or drug, which are in 2 different branch of the ontology. 

Alternative: no general "gavage" term. But 2 new terms:
-chemical treatment by gavage
-feeding by gavage 

Thanks
sabrina

**Comment by ybradford** [comment]
gavage, chemical treatment by gavage, and bacterial treatment by gavage are now available on prod
